# Generated by Django 3.1 on 2021-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=30)),
                ('profile_pic', models.ImageField(default='profile.jpg', upload_to='temp')),
                ('Phone_numb', models.CharField(default='', max_length=12)),
                ('City', models.CharField(default='', max_length=30)),
                ('skills', models.CharField(default='', max_length=15)),
                ('exp', models.IntegerField()),
                ('charge', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
