# Generated by Django 3.1 on 2021-07-25 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HireeSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiree_skills', models.CharField(default='', max_length=30)),
                ('hiree_exp', models.IntegerField()),
                ('hiree_charge', models.CharField(default='', max_length=20)),
                ('hiree_AvalArea', models.CharField(default='', max_length=30)),
                ('hiree_AvalTime', models.CharField(default='', max_length=30)),
                ('hiree_other', models.CharField(default='', max_length=30)),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HireeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=30)),
                ('profile_pic', models.ImageField(upload_to='profile')),
                ('Phone_numb', models.CharField(default='', max_length=12)),
                ('Area', models.CharField(default='', max_length=30)),
                ('City', models.CharField(default='', max_length=30)),
                ('pincode', models.CharField(default='', max_length=15)),
                ('gender', models.CharField(default='', max_length=10)),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
